export const Technologies = [
 { name: "Spring-Boot" },
 { name: "MongoDB" },
 { name: "Vue" },
 { name: "Next" },
 { name: "Nuxt" },
 { name: "PostgreSQL" },
 { name: "HTML" },
 { name: "CSS" },
 { name: "JavaScript" },
 { name: "React" },
 { name: "FastAPI" },
 { name: "Python" },
 { name: "SQL" },
 { name: "TypeScript" },
 { name: "Django" },
 { name: "Docker" },
 { name: "Postman" },
 { name: "Bootstrap" },
 { name: "TailwindCSS" },
 { name: "Java" },
 { name: "Figma" },
 { name: "Angular" },
 { name: "SCSS / SASS" },
];

